[package]
name = "cargo-caps"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
capabara = { path = "../capabara" }

cargo_metadata = "0.22"
clap = { version = "4.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "cargo-caps"
path = "src/main.rs"
