[package]
name = "cargo-caps"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
capabara = { path = "../capabara" }

anyhow.workspace = true
cargo_metadata.workspace = true
clap.workspace = true
itertools.workspace = true
serde_json.workspace = true

[[bin]]
name = "cargo-caps"
path = "src/main.rs"
